// Generated by design/ai_to_swift.py from design/ProbeHome.ai. Do not edit; rerun the script.

import SwiftUI

/// Layers of the ProbeHome.ai artboard, bottom to top, in artboard points (720 × 1600, y down).
enum HomeArt {
    static let artboard = CGRect(x: 0, y: 0, width: 720, height: 1600)

    /// Illustrator "Layer 2".
    static let background = ArtLayer(name: "Layer 2", fills: [
        ArtFill(color: Color(red: 1, green: 0.435, blue: 0.212), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 0, y: 1600))
            p.addLine(to: CGPoint(x: 719.457, y: 1600))
            p.addLine(to: CGPoint(x: 719.457, y: 0))
            p.addLine(to: CGPoint(x: 0, y: 0))
            p.closeSubpath()
        }),
    ])

    /// Illustrator "Layer 3".
    static let monster = ArtLayer(name: "Layer 3", fills: [
        ArtFill(color: Color(red: 1, green: 0.882, blue: 0), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: -15.107, y: 1053.963))
            p.addCurve(to: CGPoint(x: 301.821, y: 600.986), control1: CGPoint(x: 11.306, y: 864.491), control2: CGPoint(x: 132.876, y: 690.734))
            p.addCurve(to: CGPoint(x: 357.56, y: 666.058), control1: CGPoint(x: 336.732, y: 582.44), control2: CGPoint(x: 381.248, y: 634.408))
            p.addCurve(to: CGPoint(x: 449.44, y: 599.797), control1: CGPoint(x: 355.102, y: 621.239), control2: CGPoint(x: 407.689, y: 583.315))
            p.addCurve(to: CGPoint(x: 471.278, y: 710.952), control1: CGPoint(x: 491.19, y: 616.28), control2: CGPoint(x: 503.69, y: 679.899))
            p.addCurve(to: CGPoint(x: 619.781, y: 712.434), control1: CGPoint(x: 493.332, y: 650.137), control2: CGPoint(x: 598.945, y: 651.191))
            p.addCurve(to: CGPoint(x: 747.055, y: 1698.814), control1: CGPoint(x: 727.272, y: 1028.38), control2: CGPoint(x: 770.826, y: 1365.931))
            p.addCurve(to: CGPoint(x: 380.207, y: 2013.772), control1: CGPoint(x: 734.548, y: 1873.959), control2: CGPoint(x: 555.202, y: 1999.324))
            p.addCurve(to: CGPoint(x: -127.286, y: 1893.424), control1: CGPoint(x: 205.211, y: 2028.22), control2: CGPoint(x: 35.12, y: 1960.182))
        }),
    ])

    /// Illustrator "Layer 4".
    static let eyeWhite = ArtLayer(name: "Layer 4", fills: [
        ArtFill(color: Color(red: 0.98, green: 0.976, blue: 0.949), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 374.137, y: 892.775))
            p.addCurve(to: CGPoint(x: 244.937, y: 896.354), control1: CGPoint(x: 339.242, y: 860.697), control2: CGPoint(x: 279.44, y: 863.856))
            p.addCurve(to: CGPoint(x: 222.508, y: 1027.574), control1: CGPoint(x: 210.435, y: 928.853), control2: CGPoint(x: 202.577, y: 984.569))
            p.addCurve(to: CGPoint(x: 333.806, y: 1106.329), control1: CGPoint(x: 242.439, y: 1070.579), control2: CGPoint(x: 286.852, y: 1099.85))
            p.addCurve(to: CGPoint(x: 468.055, y: 1070.765), control1: CGPoint(x: 380.76, y: 1112.806), control2: CGPoint(x: 429.287, y: 1098.036))
            p.addCurve(to: CGPoint(x: 498.73, y: 948.564), control1: CGPoint(x: 505.488, y: 1044.436), control2: CGPoint(x: 519.29, y: 989.452))
            p.addCurve(to: CGPoint(x: 382.343, y: 900.31), control1: CGPoint(x: 478.17, y: 907.676), control2: CGPoint(x: 425.803, y: 885.966))
        }),
    ])

    /// Illustrator "Layer 5".
    static let iris = ArtLayer(name: "Layer 5", fills: [
        ArtFill(color: Color(red: 0, green: 0.584, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 302.75, y: 989.063))
            p.addCurve(to: CGPoint(x: 360, y: 931.813), control1: CGPoint(x: 302.75, y: 957.445), control2: CGPoint(x: 328.382, y: 931.813))
            p.addCurve(to: CGPoint(x: 417.25, y: 989.063), control1: CGPoint(x: 391.618, y: 931.813), control2: CGPoint(x: 417.25, y: 957.445))
            p.addCurve(to: CGPoint(x: 360, y: 1046.313), control1: CGPoint(x: 417.25, y: 1020.681), control2: CGPoint(x: 391.618, y: 1046.313))
            p.addCurve(to: CGPoint(x: 302.75, y: 989.063), control1: CGPoint(x: 328.382, y: 1046.313), control2: CGPoint(x: 302.75, y: 1020.681))
        }),
    ])

    /// Illustrator "Layer 6".
    static let pupil = ArtLayer(name: "Layer 6", fills: [
        ArtFill(color: Color(red: 0.012, green: 0.102, blue: 0.161), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 319.75, y: 989.063))
            p.addCurve(to: CGPoint(x: 360, y: 948.813), control1: CGPoint(x: 319.75, y: 966.834), control2: CGPoint(x: 337.771, y: 948.813))
            p.addCurve(to: CGPoint(x: 400.25, y: 989.063), control1: CGPoint(x: 382.229, y: 948.813), control2: CGPoint(x: 400.25, y: 966.834))
            p.addCurve(to: CGPoint(x: 360, y: 1029.313), control1: CGPoint(x: 400.25, y: 1011.292), control2: CGPoint(x: 382.229, y: 1029.313))
            p.addCurve(to: CGPoint(x: 319.75, y: 989.063), control1: CGPoint(x: 337.771, y: 1029.313), control2: CGPoint(x: 319.75, y: 1011.292))
        }),
    ])

    /// Illustrator "Layer 8".
    static let title = ArtLayer(name: "Layer 8", fills: [
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 105.206, y: 294.402))
            p.addCurve(to: CGPoint(x: 118.261, y: 293.486), control1: CGPoint(x: 107.398, y: 293.963), control2: CGPoint(x: 111.743, y: 293.486))
            p.addCurve(to: CGPoint(x: 141.931, y: 311.012), control1: CGPoint(x: 133.132, y: 293.486), control2: CGPoint(x: 141.931, y: 299.583))
            p.addCurve(to: CGPoint(x: 116.099, y: 330.738), control1: CGPoint(x: 141.931, y: 323.695), control2: CGPoint(x: 131.642, y: 330.738))
            p.addCurve(to: CGPoint(x: 105.206, y: 329.85), control1: CGPoint(x: 111.221, y: 330.738), control2: CGPoint(x: 107.846, y: 330.48))
            p.addLine(to: CGPoint(x: 105.206, y: 294.402))
            p.closeSubpath()
            p.move(to: CGPoint(x: 76.646, y: 274.578))
            p.addLine(to: CGPoint(x: 76.646, y: 394.987))
            p.addLine(to: CGPoint(x: 105.206, y: 394.987))
            p.addLine(to: CGPoint(x: 105.206, y: 351.902))
            p.addCurve(to: CGPoint(x: 116.155, y: 352.712), control1: CGPoint(x: 107.989, y: 352.389), control2: CGPoint(x: 111.82, y: 352.712))
            p.addCurve(to: CGPoint(x: 159.084, y: 339.36), control1: CGPoint(x: 134.401, y: 352.712), control2: CGPoint(x: 149.047, y: 348.474))
            p.addCurve(to: CGPoint(x: 170.491, y: 310.64), control1: CGPoint(x: 166.663, y: 332.637), control2: CGPoint(x: 170.491, y: 322.172))
            p.addCurve(to: CGPoint(x: 156.724, y: 281.941), control1: CGPoint(x: 170.491, y: 298.119), control2: CGPoint(x: 164.731, y: 287.874))
            p.addCurve(to: CGPoint(x: 118.013, y: 271.94), control1: CGPoint(x: 148.487, y: 275.635), control2: CGPoint(x: 135.869, y: 271.94))
            p.addCurve(to: CGPoint(x: 76.646, y: 274.578), control1: CGPoint(x: 98.66, y: 271.94), control2: CGPoint(x: 85.711, y: 273.168))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 189.198, y: 394.987))
            p.addLine(to: CGPoint(x: 217.758, y: 394.987))
            p.addLine(to: CGPoint(x: 217.758, y: 347.35))
            p.addLine(to: CGPoint(x: 227.506, y: 347.35))
            p.addCurve(to: CGPoint(x: 249.389, y: 366.815), control1: CGPoint(x: 240.015, y: 347.541), control2: CGPoint(x: 245.551, y: 351.546))
            p.addCurve(to: CGPoint(x: 258.531, y: 394.987), control1: CGPoint(x: 253.398, y: 382.443), control2: CGPoint(x: 256.54, y: 391.406))
            p.addLine(to: CGPoint(x: 287.919, y: 394.987))
            p.addCurve(to: CGPoint(x: 277.395, y: 360.112), control1: CGPoint(x: 285.451, y: 390.168), control2: CGPoint(x: 281.634, y: 374.013))
            p.addCurve(to: CGPoint(x: 260.602, y: 337.89), control1: CGPoint(x: 274.072, y: 349.558), control2: CGPoint(x: 269.128, y: 341.328))
            p.addLine(to: CGPoint(x: 260.602, y: 337.243))
            p.addCurve(to: CGPoint(x: 283.043, y: 307.431), control1: CGPoint(x: 270.446, y: 334.146), control2: CGPoint(x: 283.043, y: 323.679))
            p.addCurve(to: CGPoint(x: 271.218, y: 281.798), control1: CGPoint(x: 283.043, y: 295.968), control2: CGPoint(x: 278.463, y: 287.255))
            p.addCurve(to: CGPoint(x: 229.434, y: 271.94), control1: CGPoint(x: 262.229, y: 274.988), control2: CGPoint(x: 249.232, y: 271.94))
            p.addCurve(to: CGPoint(x: 189.198, y: 274.654), control1: CGPoint(x: 212.89, y: 271.94), control2: CGPoint(x: 198.521, y: 273.168))
            p.addLine(to: CGPoint(x: 189.198, y: 394.987))
            p.closeSubpath()
            p.move(to: CGPoint(x: 217.758, y: 294.154))
            p.addCurve(to: CGPoint(x: 232.393, y: 293.163), control1: CGPoint(x: 219.911, y: 293.678), control2: CGPoint(x: 224.296, y: 293.163))
            p.addCurve(to: CGPoint(x: 254.484, y: 309.735), control1: CGPoint(x: 245.657, y: 293.163), control2: CGPoint(x: 254.484, y: 298.327))
            p.addCurve(to: CGPoint(x: 230.721, y: 326.84), control1: CGPoint(x: 254.484, y: 320.341), control2: CGPoint(x: 245.527, y: 326.84))
            p.addLine(to: CGPoint(x: 217.758, y: 326.84))
            p.addLine(to: CGPoint(x: 217.758, y: 294.154))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 362.952, y: 270.854))
            p.addCurve(to: CGPoint(x: 297.213, y: 335.207), control1: CGPoint(x: 324.071, y: 270.854), control2: CGPoint(x: 297.213, y: 297.701))
            p.addCurve(to: CGPoint(x: 360.972, y: 397.159), control1: CGPoint(x: 297.213, y: 370.426), control2: CGPoint(x: 321.948, y: 397.159))
            p.addCurve(to: CGPoint(x: 427.567, y: 333.091), control1: CGPoint(x: 400.811, y: 397.159), control2: CGPoint(x: 427.567, y: 371.115))
            p.addCurve(to: CGPoint(x: 362.952, y: 270.854), control1: CGPoint(x: 427.567, y: 297.416), control2: CGPoint(x: 403.061, y: 270.854))
            p.closeSubpath()
            p.move(to: CGPoint(x: 362.447, y: 293.219))
            p.addCurve(to: CGPoint(x: 396.933, y: 333.958), control1: CGPoint(x: 384.166, y: 293.219), control2: CGPoint(x: 396.933, y: 311.82))
            p.addCurve(to: CGPoint(x: 362.475, y: 374.794), control1: CGPoint(x: 396.933, y: 357.358), control2: CGPoint(x: 383.982, y: 374.794))
            p.addCurve(to: CGPoint(x: 327.847, y: 334.417), control1: CGPoint(x: 341.149, y: 374.794), control2: CGPoint(x: 327.847, y: 357.052))
            p.addCurve(to: CGPoint(x: 362.447, y: 293.219), control1: CGPoint(x: 327.847, y: 311.514), control2: CGPoint(x: 340.69, y: 293.219))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 446.874, y: 394.416))
            p.addCurve(to: CGPoint(x: 479.273, y: 396.358), control1: CGPoint(x: 453.301, y: 395.349), control2: CGPoint(x: 464.156, y: 396.358))
            p.addCurve(to: CGPoint(x: 529.854, y: 385.662), control1: CGPoint(x: 504.848, y: 396.358), control2: CGPoint(x: 520.351, y: 392.597))
            p.addCurve(to: CGPoint(x: 543.792, y: 359.113), control1: CGPoint(x: 538.033, y: 379.624), control2: CGPoint(x: 543.792, y: 370.635))
            p.addCurve(to: CGPoint(x: 518.619, y: 328.96), control1: CGPoint(x: 543.792, y: 342.766), control2: CGPoint(x: 532.481, y: 332.482))
            p.addLine(to: CGPoint(x: 518.619, y: 328.56))
            p.addCurve(to: CGPoint(x: 539.439, y: 302.844), control1: CGPoint(x: 532.922, y: 323.542), control2: CGPoint(x: 539.439, y: 313.541))
            p.addCurve(to: CGPoint(x: 523.134, y: 278.192), control1: CGPoint(x: 539.439, y: 290.772), control2: CGPoint(x: 532.339, y: 282.403))
            p.addCurve(to: CGPoint(x: 485.328, y: 271.94), control1: CGPoint(x: 514.041, y: 273.666), control2: CGPoint(x: 503.974, y: 271.94))
            p.addCurve(to: CGPoint(x: 446.874, y: 274.654), control1: CGPoint(x: 470.343, y: 271.94), control2: CGPoint(x: 454.15, y: 273.311))
            p.addLine(to: CGPoint(x: 446.874, y: 394.416))
            p.closeSubpath()
            p.move(to: CGPoint(x: 475.434, y: 293.65))
            p.addCurve(to: CGPoint(x: 488.924, y: 292.773), control1: CGPoint(x: 477.939, y: 293.211), control2: CGPoint(x: 481.759, y: 292.773))
            p.addCurve(to: CGPoint(x: 510.27, y: 306.346), control1: CGPoint(x: 502.31, y: 292.773), control2: CGPoint(x: 510.27, y: 296.983))
            p.addCurve(to: CGPoint(x: 485.655, y: 320.813), control1: CGPoint(x: 510.27, y: 315.132), control2: CGPoint(x: 502.267, y: 320.813))
            p.addLine(to: CGPoint(x: 475.433, y: 320.813))
            p.addLine(to: CGPoint(x: 475.433, y: 293.65))
            p.closeSubpath()
            p.move(to: CGPoint(x: 475.433, y: 341.18))
            p.addLine(to: CGPoint(x: 486.289, y: 341.18))
            p.addCurve(to: CGPoint(x: 513.301, y: 357.763), control1: CGPoint(x: 501.495, y: 341.18), control2: CGPoint(x: 513.301, y: 345.574))
            p.addCurve(to: CGPoint(x: 487.772, y: 375.24), control1: CGPoint(x: 513.301, y: 370.772), control2: CGPoint(x: 501.245, y: 375.24))
            p.addCurve(to: CGPoint(x: 475.433, y: 374.725), control1: CGPoint(x: 482.246, y: 375.24), control2: CGPoint(x: 478.454, y: 375.202))
            p.addLine(to: CGPoint(x: 475.433, y: 341.18))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 642.827, y: 320.813))
            p.addLine(to: CGPoint(x: 592.252, y: 320.813))
            p.addLine(to: CGPoint(x: 592.252, y: 296.285))
            p.addLine(to: CGPoint(x: 645.904, y: 296.285))
            p.addLine(to: CGPoint(x: 645.904, y: 273.026))
            p.addLine(to: CGPoint(x: 563.407, y: 273.026))
            p.addLine(to: CGPoint(x: 563.407, y: 394.987))
            p.addLine(to: CGPoint(x: 648.694, y: 394.987))
            p.addLine(to: CGPoint(x: 648.694, y: 371.728))
            p.addLine(to: CGPoint(x: 592.252, y: 371.728))
            p.addLine(to: CGPoint(x: 592.252, y: 344.072))
            p.addLine(to: CGPoint(x: 642.827, y: 344.072))
            p.addLine(to: CGPoint(x: 642.827, y: 320.813))
            p.closeSubpath()
        }),
    ])

    /// Every layer in drawing order.
    static let layers = [background, monster, eyeWhite, iris, pupil, title]
}
