// Generated by design/ai_to_swift.py from design/MainScreen.ai. Do not edit; rerun the script.

import SwiftUI

/// Layers of the MainScreen.ai artboard, bottom to top, in artboard points (720 × 1600, y down).
enum MainArt {
    static let artboard = CGRect(x: 0, y: 0, width: 720, height: 1600)

    /// Illustrator "Layer 1".
    static let background = ArtLayer(name: "Layer 1", fills: [
        ArtFill(color: Color(red: 0.169, green: 0.729, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 0, y: 1600))
            p.addLine(to: CGPoint(x: 720, y: 1600))
            p.addLine(to: CGPoint(x: 720, y: 0))
            p.addLine(to: CGPoint(x: 0, y: 0))
            p.closeSubpath()
        }),
    ])

    /// Illustrator "Layer 2".
    static let findCard = ArtLayer(name: "Layer 2", fills: [
        ArtFill(color: Color(red: 0, green: 0.098, blue: 0.651), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 55, y: 887.987))
            p.addLine(to: CGPoint(x: 55, y: 575.892))
            p.addCurve(to: CGPoint(x: 75.953, y: 554.94), control1: CGPoint(x: 55, y: 564.32), control2: CGPoint(x: 64.381, y: 554.94))
            p.addLine(to: CGPoint(x: 644.047, y: 554.94))
            p.addCurve(to: CGPoint(x: 665, y: 575.892), control1: CGPoint(x: 655.619, y: 554.94), control2: CGPoint(x: 665, y: 564.32))
            p.addLine(to: CGPoint(x: 665, y: 887.987))
            p.addCurve(to: CGPoint(x: 644.047, y: 908.94), control1: CGPoint(x: 665, y: 899.559), control2: CGPoint(x: 655.619, y: 908.94))
            p.addLine(to: CGPoint(x: 75.953, y: 908.94))
            p.addCurve(to: CGPoint(x: 55, y: 887.987), control1: CGPoint(x: 64.381, y: 908.94), control2: CGPoint(x: 55, y: 899.559))
        }),
    ])

    /// Illustrator "Layer 5".
    static let findLabel = ArtLayer(name: "Layer 5", fills: [
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 198.693, y: 880.409))
            p.addLine(to: CGPoint(x: 198.693, y: 859.333))
            p.addLine(to: CGPoint(x: 163.173, y: 859.333))
            p.addLine(to: CGPoint(x: 163.173, y: 823.283))
            p.addLine(to: CGPoint(x: 146.178, y: 823.283))
            p.addLine(to: CGPoint(x: 146.178, y: 859.333))
            p.addLine(to: CGPoint(x: 126.572, y: 859.333))
            p.addLine(to: CGPoint(x: 126.572, y: 820.756))
            p.addLine(to: CGPoint(x: 109.578, y: 820.756))
            p.addLine(to: CGPoint(x: 109.578, y: 880.409))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 109.577, y: 804.78))
            p.addLine(to: CGPoint(x: 198.693, y: 804.78))
            p.addLine(to: CGPoint(x: 198.693, y: 783.704))
            p.addLine(to: CGPoint(x: 109.577, y: 783.704))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 198.693, y: 745.79))
            p.addLine(to: CGPoint(x: 169.654, y: 745.79))
            p.addCurve(to: CGPoint(x: 131.233, y: 746.583), control1: CGPoint(x: 156.224, y: 745.79), control2: CGPoint(x: 143.993, y: 745.922))
            p.addLine(to: CGPoint(x: 131.178, y: 746.083))
            p.addCurve(to: CGPoint(x: 164.233, y: 728.475), control1: CGPoint(x: 142.447, y: 741.01), control2: CGPoint(x: 153.92, y: 734.552))
            p.addLine(to: CGPoint(x: 198.693, y: 707.509))
            p.addLine(to: CGPoint(x: 198.693, y: 684.667))
            p.addLine(to: CGPoint(x: 109.578, y: 684.667))
            p.addLine(to: CGPoint(x: 109.578, y: 704.256))
            p.addLine(to: CGPoint(x: 137.655, y: 704.256))
            p.addCurve(to: CGPoint(x: 173.548, y: 702.677), control1: CGPoint(x: 150.155, y: 704.256), control2: CGPoint(x: 160.941, y: 704.124))
            p.addLine(to: CGPoint(x: 173.604, y: 703.046))
            p.addCurve(to: CGPoint(x: 141.509, y: 719.283), control1: CGPoint(x: 162.751, y: 707.569), control2: CGPoint(x: 151.677, y: 713.067))
            p.addLine(to: CGPoint(x: 109.578, y: 739.381))
            p.addLine(to: CGPoint(x: 109.578, y: 765.379))
            p.addLine(to: CGPoint(x: 198.693, y: 765.379))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 198.276, y: 666.347))
            p.addCurve(to: CGPoint(x: 199.695, y: 640.602), control1: CGPoint(x: 199.041, y: 660.868), control2: CGPoint(x: 199.695, y: 652.734))
            p.addCurve(to: CGPoint(x: 187.18, y: 594.885), control1: CGPoint(x: 199.695, y: 621.576), control2: CGPoint(x: 195.678, y: 605.356))
            p.addCurve(to: CGPoint(x: 151.631, y: 579.356), control1: CGPoint(x: 179.871, y: 586.046), control2: CGPoint(x: 168.38, y: 579.356))
            p.addCurve(to: CGPoint(x: 118.893, y: 595.592), control1: CGPoint(x: 136.374, y: 579.356), control2: CGPoint(x: 125.811, y: 585.789))
            p.addCurve(to: CGPoint(x: 108.784, y: 635.99), control1: CGPoint(x: 112.064, y: 605.069), control2: CGPoint(x: 108.784, y: 617.187))
            p.addCurve(to: CGPoint(x: 110.767, y: 666.347), control1: CGPoint(x: 108.784, y: 647.157), control2: CGPoint(x: 109.501, y: 657.893))
            p.addLine(to: CGPoint(x: 198.276, y: 666.347))
            p.closeSubpath()
            p.move(to: CGPoint(x: 125.725, y: 645.271))
            p.addCurve(to: CGPoint(x: 124.841, y: 634.224), control1: CGPoint(x: 125.321, y: 643.25), control2: CGPoint(x: 124.841, y: 639.691))
            p.addCurve(to: CGPoint(x: 152.701, y: 601.816), control1: CGPoint(x: 124.841, y: 614.628), control2: CGPoint(x: 134.118, y: 601.76))
            p.addCurve(to: CGPoint(x: 183.43, y: 636.938), control1: CGPoint(x: 172.92, y: 601.816), control2: CGPoint(x: 183.638, y: 615.394))
            p.addCurve(to: CGPoint(x: 183.053, y: 645.271), control1: CGPoint(x: 183.43, y: 639.907), control2: CGPoint(x: 183.402, y: 643.229))
            p.addLine(to: CGPoint(x: 125.725, y: 645.271))
            p.closeSubpath()
        }),
    ])

    /// Illustrator "Layer 3".
    static let findEyes = ArtLayer(name: "Layer 3", fills: [
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 353.197, y: 651.312))
            p.addCurve(to: CGPoint(x: 257.647, y: 712.725), control1: CGPoint(x: 312.213, y: 643.202), control2: CGPoint(x: 267.445, y: 671.975))
            p.addCurve(to: CGPoint(x: 314.773, y: 811.107), control1: CGPoint(x: 247.848, y: 753.475), control2: CGPoint(x: 274.613, y: 799.569))
            p.addCurve(to: CGPoint(x: 415.129, y: 757.97), control1: CGPoint(x: 354.933, y: 822.645), control2: CGPoint(x: 401.952, y: 797.749))
            p.addCurve(to: CGPoint(x: 366.444, y: 655.118), control1: CGPoint(x: 428.305, y: 718.191), control2: CGPoint(x: 405.495, y: 670.002))
        }),
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 562.718, y: 660.838))
            p.addCurve(to: CGPoint(x: 457.671, y: 700.52), control1: CGPoint(x: 524.805, y: 644.006), control2: CGPoint(x: 475.111, y: 662.778))
            p.addCurve(to: CGPoint(x: 495.354, y: 806.618), control1: CGPoint(x: 440.23, y: 738.262), control2: CGPoint(x: 458.057, y: 788.453))
            p.addCurve(to: CGPoint(x: 601.731, y: 770.683), control1: CGPoint(x: 532.65, y: 824.783), control2: CGPoint(x: 582.974, y: 807.783))
            p.addCurve(to: CGPoint(x: 567.805, y: 663.316), control1: CGPoint(x: 620.489, y: 733.582), control2: CGPoint(x: 604.44, y: 682.791))
        }),
    ])

    /// Illustrator "Layer 4".
    static let findPupils = ArtLayer(name: "Layer 4", fills: [
        ArtFill(color: Color(red: 0, green: 0, blue: 0), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 335.765, y: 734.284))
            p.addCurve(to: CGPoint(x: 372.984, y: 696.935), control1: CGPoint(x: 335.765, y: 713.658), control2: CGPoint(x: 352.429, y: 696.935))
            p.addCurve(to: CGPoint(x: 410.204, y: 734.284), control1: CGPoint(x: 393.54, y: 696.935), control2: CGPoint(x: 410.204, y: 713.658))
            p.addCurve(to: CGPoint(x: 372.984, y: 771.634), control1: CGPoint(x: 410.204, y: 754.911), control2: CGPoint(x: 393.54, y: 771.634))
            p.addCurve(to: CGPoint(x: 335.765, y: 734.284), control1: CGPoint(x: 352.429, y: 771.634), control2: CGPoint(x: 335.765, y: 754.911))
        }),
        ArtFill(color: Color(red: 0, green: 0, blue: 0), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 526.796, y: 734.284))
            p.addCurve(to: CGPoint(x: 564.015, y: 696.935), control1: CGPoint(x: 526.796, y: 713.658), control2: CGPoint(x: 543.46, y: 696.935))
            p.addCurve(to: CGPoint(x: 601.235, y: 734.284), control1: CGPoint(x: 584.571, y: 696.935), control2: CGPoint(x: 601.235, y: 713.658))
            p.addCurve(to: CGPoint(x: 564.015, y: 771.634), control1: CGPoint(x: 601.235, y: 754.911), control2: CGPoint(x: 584.571, y: 771.634))
            p.addCurve(to: CGPoint(x: 526.796, y: 734.284), control1: CGPoint(x: 543.46, y: 771.634), control2: CGPoint(x: 526.796, y: 754.911))
        }),
    ])

    /// Illustrator "Layer 6".
    static let analyzeCard = ArtLayer(name: "Layer 6", fills: [
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 55, y: 1309.426))
            p.addLine(to: CGPoint(x: 55, y: 997.331))
            p.addCurve(to: CGPoint(x: 75.953, y: 976.379), control1: CGPoint(x: 55, y: 985.759), control2: CGPoint(x: 64.381, y: 976.379))
            p.addLine(to: CGPoint(x: 644.047, y: 976.379))
            p.addCurve(to: CGPoint(x: 665, y: 997.331), control1: CGPoint(x: 655.619, y: 976.379), control2: CGPoint(x: 665, y: 985.759))
            p.addLine(to: CGPoint(x: 665, y: 1309.426))
            p.addCurve(to: CGPoint(x: 644.047, y: 1330.379), control1: CGPoint(x: 665, y: 1320.998), control2: CGPoint(x: 655.619, y: 1330.379))
            p.addLine(to: CGPoint(x: 75.953, y: 1330.379))
            p.addCurve(to: CGPoint(x: 55, y: 1309.426), control1: CGPoint(x: 64.381, y: 1330.379), control2: CGPoint(x: 55, y: 1320.998))
        }),
    ])

    /// Illustrator "Layer 7".
    static let analyzeLabel = ArtLayer(name: "Layer 7", fills: [
        ArtFill(color: Color(red: 0, green: 0.098, blue: 0.651), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 162.217, y: 1284.088))
            p.addLine(to: CGPoint(x: 175.191, y: 1279.785))
            p.addLine(to: CGPoint(x: 175.191, y: 1267.031))
            p.addLine(to: CGPoint(x: 126.457, y: 1284.102))
            p.addLine(to: CGPoint(x: 126.457, y: 1299.547))
            p.addLine(to: CGPoint(x: 175.191, y: 1315.85))
            p.addLine(to: CGPoint(x: 175.191, y: 1303.723))
            p.addLine(to: CGPoint(x: 162.217, y: 1299.85))
            p.closeSubpath()
            p.move(to: CGPoint(x: 153.721, y: 1285.986))
            p.addLine(to: CGPoint(x: 153.721, y: 1298.05))
            p.addLine(to: CGPoint(x: 143.324, y: 1294.758))
            p.addCurve(to: CGPoint(x: 134.493, y: 1292.368), control1: CGPoint(x: 140.489, y: 1293.887), control2: CGPoint(x: 137.237, y: 1293.148))
            p.addLine(to: CGPoint(x: 134.493, y: 1292.224))
            p.addCurve(to: CGPoint(x: 143.313, y: 1289.491), control1: CGPoint(x: 137.221, y: 1291.386), control2: CGPoint(x: 140.459, y: 1290.451))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 0, green: 0.098, blue: 0.651), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 175.191, y: 1249.423))
            p.addLine(to: CGPoint(x: 159.311, y: 1249.423))
            p.addCurve(to: CGPoint(x: 138.299, y: 1249.857), control1: CGPoint(x: 151.966, y: 1249.423), control2: CGPoint(x: 145.277, y: 1249.495))
            p.addLine(to: CGPoint(x: 138.269, y: 1249.583))
            p.addCurve(to: CGPoint(x: 156.346, y: 1239.954), control1: CGPoint(x: 144.432, y: 1246.809), control2: CGPoint(x: 150.706, y: 1243.277))
            p.addLine(to: CGPoint(x: 175.191, y: 1228.488))
            p.addLine(to: CGPoint(x: 175.191, y: 1215.997))
            p.addLine(to: CGPoint(x: 126.457, y: 1215.997))
            p.addLine(to: CGPoint(x: 126.457, y: 1226.709))
            p.addLine(to: CGPoint(x: 141.811, y: 1226.709))
            p.addCurve(to: CGPoint(x: 161.44, y: 1225.846), control1: CGPoint(x: 148.647, y: 1226.709), control2: CGPoint(x: 154.545, y: 1226.637))
            p.addLine(to: CGPoint(x: 161.47, y: 1226.048))
            p.addCurve(to: CGPoint(x: 143.919, y: 1234.927), control1: CGPoint(x: 155.535, y: 1228.521), control2: CGPoint(x: 149.479, y: 1231.528))
            p.addLine(to: CGPoint(x: 126.457, y: 1245.918))
            p.addLine(to: CGPoint(x: 126.457, y: 1260.136))
            p.addLine(to: CGPoint(x: 175.191, y: 1260.136))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 0, green: 0.098, blue: 0.651), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 162.217, y: 1177.726))
            p.addLine(to: CGPoint(x: 175.191, y: 1173.423))
            p.addLine(to: CGPoint(x: 175.191, y: 1160.669))
            p.addLine(to: CGPoint(x: 126.457, y: 1177.739))
            p.addLine(to: CGPoint(x: 126.457, y: 1193.185))
            p.addLine(to: CGPoint(x: 175.191, y: 1209.488))
            p.addLine(to: CGPoint(x: 175.191, y: 1197.361))
            p.addLine(to: CGPoint(x: 162.217, y: 1193.487))
            p.closeSubpath()
            p.move(to: CGPoint(x: 153.721, y: 1179.624))
            p.addLine(to: CGPoint(x: 153.721, y: 1191.688))
            p.addLine(to: CGPoint(x: 143.324, y: 1188.396))
            p.addCurve(to: CGPoint(x: 134.493, y: 1186.006), control1: CGPoint(x: 140.489, y: 1187.524), control2: CGPoint(x: 137.237, y: 1186.786))
            p.addLine(to: CGPoint(x: 134.493, y: 1185.861))
            p.addCurve(to: CGPoint(x: 143.313, y: 1183.129), control1: CGPoint(x: 137.221, y: 1185.024), control2: CGPoint(x: 140.459, y: 1184.088))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 0, green: 0.098, blue: 0.651), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 175.191, y: 1153.773))
            p.addLine(to: CGPoint(x: 175.191, y: 1120.549))
            p.addLine(to: CGPoint(x: 165.555, y: 1120.549))
            p.addLine(to: CGPoint(x: 165.555, y: 1142.247))
            p.addLine(to: CGPoint(x: 126.457, y: 1142.247))
            p.addLine(to: CGPoint(x: 126.457, y: 1153.773))
            p.addLine(to: CGPoint(x: 175.191, y: 1153.773))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 0, green: 0.098, blue: 0.651), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 175.191, y: 1096.399))
            p.addLine(to: CGPoint(x: 154.397, y: 1096.399))
            p.addLine(to: CGPoint(x: 126.457, y: 1078.592))
            p.addLine(to: CGPoint(x: 126.457, y: 1091.879))
            p.addLine(to: CGPoint(x: 138.277, y: 1097.474))
            p.addCurve(to: CGPoint(x: 147.217, y: 1101.609), control1: CGPoint(x: 141.71, y: 1099.061), control2: CGPoint(x: 144.336, y: 1100.36))
            p.addLine(to: CGPoint(x: 147.217, y: 1101.753))
            p.addCurve(to: CGPoint(x: 138.22, y: 1105.915), control1: CGPoint(x: 144.104, y: 1103.105), control2: CGPoint(x: 141.839, y: 1104.228))
            p.addLine(to: CGPoint(x: 126.457, y: 1111.417))
            p.addLine(to: CGPoint(x: 126.457, y: 1124.875))
            p.addLine(to: CGPoint(x: 154.766, y: 1107.925))
            p.addLine(to: CGPoint(x: 175.191, y: 1107.925))
            p.addLine(to: CGPoint(x: 175.191, y: 1096.399))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 0, green: 0.098, blue: 0.651), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 175.191, y: 1075.649))
            p.addLine(to: CGPoint(x: 175.191, y: 1033.859))
            p.addLine(to: CGPoint(x: 165.783, y: 1033.859))
            p.addLine(to: CGPoint(x: 165.783, y: 1059.731))
            p.addLine(to: CGPoint(x: 165.509, y: 1059.731))
            p.addLine(to: CGPoint(x: 132.621, y: 1034.366))
            p.addLine(to: CGPoint(x: 126.457, y: 1034.366))
            p.addLine(to: CGPoint(x: 126.457, y: 1073.3))
            p.addLine(to: CGPoint(x: 135.865, y: 1073.3))
            p.addLine(to: CGPoint(x: 135.865, y: 1049.843))
            p.addLine(to: CGPoint(x: 136.139, y: 1049.843))
            p.addLine(to: CGPoint(x: 169.098, y: 1075.649))
            p.closeSubpath()
        }),
        ArtFill(color: Color(red: 0, green: 0.098, blue: 0.651), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 145.552, y: 994.634))
            p.addLine(to: CGPoint(x: 145.552, y: 1014.843))
            p.addLine(to: CGPoint(x: 135.751, y: 1014.843))
            p.addLine(to: CGPoint(x: 135.751, y: 993.405))
            p.addLine(to: CGPoint(x: 126.457, y: 993.405))
            p.addLine(to: CGPoint(x: 126.457, y: 1026.37))
            p.addLine(to: CGPoint(x: 175.191, y: 1026.37))
            p.addLine(to: CGPoint(x: 175.191, y: 992.29))
            p.addLine(to: CGPoint(x: 165.897, y: 992.29))
            p.addLine(to: CGPoint(x: 165.897, y: 1014.843))
            p.addLine(to: CGPoint(x: 154.846, y: 1014.843))
            p.addLine(to: CGPoint(x: 154.846, y: 994.634))
            p.addLine(to: CGPoint(x: 145.552, y: 994.634))
            p.closeSubpath()
        }),
    ])

    /// Illustrator "Layer 8".
    static let magnifier = ArtLayer(name: "Layer 8", fills: [
        ArtFill(color: Color(red: 0.847, green: 0.851, blue: 0.89), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 300.941, y: 1136.959))
            p.addCurve(to: CGPoint(x: 427.272, y: 1009.855), control1: CGPoint(x: 300.941, y: 1066.762), control2: CGPoint(x: 357.501, y: 1009.855))
            p.addCurve(to: CGPoint(x: 553.603, y: 1136.959), control1: CGPoint(x: 497.043, y: 1009.855), control2: CGPoint(x: 553.603, y: 1066.762))
            p.addCurve(to: CGPoint(x: 427.272, y: 1264.063), control1: CGPoint(x: 553.603, y: 1207.156), control2: CGPoint(x: 497.043, y: 1264.063))
            p.addCurve(to: CGPoint(x: 300.941, y: 1136.959), control1: CGPoint(x: 357.501, y: 1264.063), control2: CGPoint(x: 300.941, y: 1207.156))
        }),
        ArtFill(color: Color(red: 0.847, green: 0.851, blue: 0.89), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 561.411, y: 1387.856))
            p.addLine(to: CGPoint(x: 424.523, y: 1176.208))
            p.addLine(to: CGPoint(x: 464.054, y: 1150.327))
            p.addLine(to: CGPoint(x: 600.942, y: 1361.975))
            p.closeSubpath()
        }),
    ])

    /// Illustrator "Layer 9".
    static let magnifierLens = ArtLayer(name: "Layer 9", fills: [
        ArtFill(color: Color(red: 1, green: 1, blue: 1), evenOdd: false, path: Path { p in
            p.move(to: CGPoint(x: 318.628, y: 1136.959))
            p.addCurve(to: CGPoint(x: 427.273, y: 1027.65), control1: CGPoint(x: 318.628, y: 1076.589), control2: CGPoint(x: 367.27, y: 1027.65))
            p.addCurve(to: CGPoint(x: 535.917, y: 1136.959), control1: CGPoint(x: 487.275, y: 1027.65), control2: CGPoint(x: 535.917, y: 1076.589))
            p.addCurve(to: CGPoint(x: 427.273, y: 1246.268), control1: CGPoint(x: 535.917, y: 1197.329), control2: CGPoint(x: 487.275, y: 1246.268))
            p.addCurve(to: CGPoint(x: 318.628, y: 1136.959), control1: CGPoint(x: 367.27, y: 1246.268), control2: CGPoint(x: 318.628, y: 1197.329))
        }),
    ])

    /// Every layer in drawing order.
    static let layers = [background, findCard, findLabel, findEyes, findPupils, analyzeCard, analyzeLabel, magnifier, magnifierLens]
}
